// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHmBr9IU1KHJ8cqwUeRO3SXwmyhmklUiA',
    appId: '1:270373666210:web:c75d9820a897b9e44606fb',
    messagingSenderId: '270373666210',
    projectId: 'driveis-35e7f',
    authDomain: 'driveis-35e7f.firebaseapp.com',
    storageBucket: 'driveis-35e7f.firebasestorage.app',
    measurementId: 'G-MQNPHDKR8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4PScBNEFrGY_F1AFtBUk1tstLOGfDLdg',
    appId: '1:270373666210:android:32efb0a8527278114606fb',
    messagingSenderId: '270373666210',
    projectId: 'driveis-35e7f',
    storageBucket: 'driveis-35e7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIpf5T2iYoRQAaI1bRRqiBAejeROBtmMU',
    appId: '1:270373666210:ios:7d023127aa40e4ab4606fb',
    messagingSenderId: '270373666210',
    projectId: 'driveis-35e7f',
    storageBucket: 'driveis-35e7f.firebasestorage.app',
    iosBundleId: 'com.example.driveis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIpf5T2iYoRQAaI1bRRqiBAejeROBtmMU',
    appId: '1:270373666210:ios:7d023127aa40e4ab4606fb',
    messagingSenderId: '270373666210',
    projectId: 'driveis-35e7f',
    storageBucket: 'driveis-35e7f.firebasestorage.app',
    iosBundleId: 'com.example.driveis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHmBr9IU1KHJ8cqwUeRO3SXwmyhmklUiA',
    appId: '1:270373666210:web:2d7dd121d803b6074606fb',
    messagingSenderId: '270373666210',
    projectId: 'driveis-35e7f',
    authDomain: 'driveis-35e7f.firebaseapp.com',
    storageBucket: 'driveis-35e7f.firebasestorage.app',
    measurementId: 'G-WB5Y53C5JF',
  );
}
